modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="minelittleflawless"
version="0.3.0"
displayName="Mine Little Flawless"
displayURL="https://github.com/SymphonyDawn3/MineLittleFlawless"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SymphonyDawn3"
description="In this Minecraft mod, you will experience the ways that you can make friends, defeat foes, and conquer your Minecraft world with Mine Little Flawless!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.minelittleflawless]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.minelittleflawless]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration